#
# This file is structured to be consumed by both humans and computers.
# To update the generated Markdown, run `bundle exec rake maintainers:generate`
# To synchronize the maintainers with the github teams, run `bundle exec rake maintainers:synchronize`
# It is a TOML document containing Markdown
#
[Preamble]
  title = "Maintainers"
  text = """
This file lists how the ChefDK project is maintained. When making changes to the system, this
file tells you who needs to review your patch - you need a simple majority of maintainers
for the relevant subsystems to provide a :+1: on your pull request. Additionally, you need
to not receive a veto from a Lieutenant or the Project Lead. ChefDK also has an internal Clients
Pool team of all members have maintainership authority.

Check out [How Chef is Maintained](https://github.com/chef/chef-rfc/blob/master/rfc030-maintenance-policy.md#how-the-project-is-maintained) for details on the process, how to become
a maintainer, lieutenant, or the project lead.
"""

[Org]
  [Org.Lead]
    title = "Project Lead"
    person = "adamhjk"

  [Org.Components]
    title = "Components"

    [Org.Components.ChefDK]
      title = "ChefDK"
      team = "chef-dk-maintainers"
      text = "Chef Development Kit"

      paths = [
        "lib/chef-dk/",
      ]

      lieutenant = "danielsdeleo"

      maintainers = [
        "danielsdeleo",
        "jkeiser",
        "jtimberman",
        "lamont-granquist",
        "stevendanna",
      ]

[people]
  [people.adamhjk]
    Name = "Adam Jacob"
    GitHub = "adamhjk"

  [people.adamleff]
    Name = "Adam Leff"
    GitHub = "adamleff"

  [people.Aevin1387]
    Name = "Cory Stephenson"
    GitHub = "Aevin1387"

  [people.AgentMeerkat]
    Name = "Bryant Lippert"
    GitHub = "AgentMeerkat"

  [people.btm]
    Name = "Bryan McLellan"
    GitHub = "btm"

  [people.danielsdeleo]
    Name = "Daniel DeLeo"
    GitHub = "danielsdeleo"

  [people.fujin]
    Name = "AJ Christensen"
    GitHub = "fujin"

  [people.jaymzh]
    Name = "Phil Dibowitz"
    GitHub = "jaymzh"

  [people.jaym]
    Name = "Jay Mundrawala"
    GitHub = "jaym"

  [people.jonlives]
    Name = "Jon Cowie"
    GitHub = "jonlives"

  [people.jtimberman]
    Name = "Joshua Timberman"
    GitHub = "jtimberman"

  [people.lamont-granquist]
    Name = "Lamont Granquist"
    GitHub = "lamont-granquist"

  [people.martinisoft]
    Name = "Aaron Kalin"
    GitHub = "martinisoft"

  [people.mcquin]
    Name = "Claire McQuin"
    GitHub = "mcquin"

  [people.ranjib]
    Name = "Ranjib Dey"
    GitHub = "ranjib"

  [people.sethvargo]
    Name = "Seth Vargo"
    GitHub = "sethvargo"

  [people.smurawski]
    Name = "Steven Murawski"
    GitHub = "smurawski"

  [people.stevendanna]
    Name = "Steven Danna"
    GitHub = "stevendanna"

  [people.tBunnyMan]
    Name = "David Aronsohn"
    GitHub = "tbunnyman"
    IRC = "tBunnyMan"
    Twitter = "OnlyHaveCans"

  [people.thommay]
    Name = "Thom May"
    GitHub = "thommay"
    IRC = "thom"
    Twitter = "thommay"

  [people.tyler-ball]
    Name = "Tyler Ball"
    GitHub = "tyler-ball"

  [people.ksubrama]
    Name = "Kartik Cating-Subramanian"
    GitHub = "ksubrama"

  [people.joemiller]
    Name = "Joe Miller"
    GitHub = "joemiller"

  [people.coderanger]
    Name = "Noah Kantrowitz"
    GitHub = "coderanger"

  [people.ryancragun]
    Name = "Ryan Cragun"
    GitHub = "ryancragun"

  [people.chefsalim]
    Name = "Salim Alam"
    GitHub = "chefsalim"

  [people.mwrock]
    Name = "Matt Wrock"
    GitHub = "mwrock"

  [people.tas50]
    Name = "Tim Smith"
    GitHub = "tas50"
    Twitter = "tas50"
    IRC = "tas50"

  [people.jkeiser]
    Name = "John Keiser"
    GitHub = "jkeiser"

  [people.stuartpreston]
    Name = "Stuart Preston"
    GitHub = "stuartpreston"

  [people.jjasghar]
    Name = "JJ Asghar"
    GitHub = "jjasghar"
    Twitter = "jjasghar"
    IRC = "j^2"

  [people.joaogbcravo]
    Name = "João Cravo"
    GitHub = "joaogbcravo"
    Twitter = "joaogbcravo"

  [people.thehar]
    Name = "Harley Alaniz"
    GitHub = "thehar"
