# THIS IS NOW HAND MANAGED, JUST EDIT THE THING
# Buildkite consume this so keep it machine-parsable.

override "libffi", version: "3.3"
override "libiconv", version: "1.16"
override "liblzma", version: "5.2.5"
override "libxml2", version: "2.9.10"
override "libxslt", version: "1.1.34"
override "libyaml", version: "0.1.7"
override "libzmq", version: "4.0.7"
override "makedepend", version: "1.0.5"
override "ncurses", version: "5.9"
override "openssl", version: "1.0.2w"
override "pkg-config-lite", version: "0.28-1"
override "ruby", version: "2.6.6"
override "ruby-windows-devkit-bash", version: "3.1.23-4-msys-1.0.18"
override "rust", version: "1.37.0"
override "util-macros", version: "1.19.0"
override "xproto", version: "7.0.28"
override "zlib", version: "1.2.11"
