# Generated by "rake dependencies". Do not edit.
override :rubygems, version: nil
override :bundler, version: nil
override :libedit, version: "20130712-3.1"
override :libtool, version: "2.4.2"
override :libxslt, version: "1.1.28"
override :makedepend, version: "1.0.5"
override :ruby, version: "2.1.8"
override :"util-macros", version: "1.19.0"
override :xproto, version: "7.0.28"
override :zlib, version: "1.2.8"
