#
# NOTE: this runs the omnibus cookbook, but does not actually run Omnibus. Use
# 'kichen converge' to setup the virtual machine and then `kitchen login` to
# SSH into the machine and run Omnibus.
#

driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 4
    memory: 4096
  synced_folders:
    - ['..', '/home/vagrant/chef-dk']
    - ['../../omnibus', '/home/vagrant/omnibus']
    - ['../../omnibus-software', '/home/vagrant/omnibus-software']

provisioner:
  name: chef_zero
  require_chef_omnibus: true # Always install the latest version of Chef
  attributes:
    vagrant:
      this_key_exists_so_we_have_a_vagrant_key: true
    omnibus:
      build_user:          vagrant
      build_user_group:    vagrant
      build_user_password: vagrant
      install_dir: /opt/chefdk

platforms:
  - name: centos-6.7
    run_list: yum-epel::default
  - name: centos-7.3
    run_list: yum-epel::default
  - name: debian-7.9
    run_list: apt::default
  - name: debian-8.2
    run_list: apt::default
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default
  # The following (private) boxes are shared via Atlas and are only
  # available to users working for Chef. Sorry, it's about software licensing.
  #
  # Chef-internal users, you will need to:
  # 1.  Create an Atlas account:  https://atlas.hashicorp.com/
  # 2.  Ping #eng-services-support with your Atlas account name
  #     to be added to the relevant team in Atlas,
  # 3.  Do `vagrant login` with your Atlas creds so that you can download
  #     the private boxes.
  #
  # The Mac OS X boxes are VMware only also. You can enable VMware Fusion
  # by activating the `.kitchen.vmware.yml` file with the `KITCHEN_LOCAL_YAML`
  # environment variable:
  #
  #   KITCHEN_LOCAL_YAML=.kitchen.vmware.yml kitchen converge chefdk-macosx-109
  #
  - name: macosx-10.9
    driver:
      box: chef/macosx-10.9 # private
  - name: macosx-10.10
    driver:
      box: chef/macosx-10.10 # private
  - name: macosx-10.11
    driver:
      box: chef/macosx-10.11 # private
  # By adding an `i386` to the name the Omnibus cookbook's `load-omnibus-toolchain.bat`
  # will load the 32-bit version of the MinGW toolchain.
  - name: windows-2012r2-standard-i386
    provisioner:
      attributes:
        omnibus:
          build_user:          vagrant
          build_user_group:    Administrators
          build_user_password: vagrant
          install_dir: /opscode/chefdk
    driver:
      box: chef/windows-server-2012r2-standard # private
      synced_folders:
      # We have to mount this repos enclosing folder as the Omnibus build
      # gets cranky if the mounted ChefDK source folder is a symlink. This
      # mounts at `C:\vagrant\code` and the ChefDK source folder is available
      # at `C:\vagrant\code\chef-dk`
      - ['../..', '/vagrant/code']

suites:
  - name: chefdk
    run_list:
      - omnibus::default
