source "https://rubygems.org"

gem "omnibus", git: "https://github.com/chef/omnibus.git", branch: "lcg/improve-appbundling"
gem "omnibus-software", git: "https://github.com/chef/omnibus-software.git"

gem "pedump"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "test-kitchen"
  gem "kitchen-vagrant"
  gem "winrm-elevated"
end

# TODO remove this when we update Chef to use the new api exposed in 3.5.1
gem "rspec-core", "= 3.4.4"
