source "https://rubygems.org"

gem "omnibus", git: "https://github.com/chef/omnibus.git", branch: "master"
gem "omnibus-software", git: "https://github.com/chef/omnibus-software.git", branch: "master"
gem "artifactory"

gem "pedump"

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem "berkshelf", ">= 7.0"

  # Use Test Kitchen with Vagrant for converging the build environment
  gem "test-kitchen", ">= 1.23"
  gem "kitchen-vagrant"
  gem "winrm-elevated"
end
