source 'https://rubygems.org'

gem 'omnibus', git: 'https://github.com/chef/omnibus.git'
gem 'omnibus-software', git: 'https://github.com/chef/omnibus-software.git', branch: "netssh_30_pin"

# pedump pessimistically pins multipart-post to a version from 2013 which makes
# bundler very unhappy. Remove this when upstream has merged zed-0xff/pedump#6 .
gem 'pedump', git: 'https://github.com/ksubrama/pedump.git', branch: 'patch-1'

# This development group is installed by default when you run `bundle install`,
# but if you are using Omnibus in a CI-based infrastructure, you do not need
# the Test Kitchen-based build lab. You can skip these unnecessary dependencies
# by running `bundle install --without development` to speed up build times.
group :development do
  # Use Berkshelf for resolving cookbook dependencies
  gem 'berkshelf'

  # Use Test Kitchen with Vagrant for converging the build environment
  gem 'test-kitchen'
  gem 'kitchen-vagrant'
  gem 'winrm-fs'
end
