source "https://rubygems.org"

gem "chef-acceptance", github: "chef/chef-acceptance"
gem "test-kitchen"
gem "kitchen-ec2"
gem "kitchen-inspec"
gem "kitchen-vagrant"
gem "windows_chef_zero"
gem "winrm-fs"
gem "winrm-elevated"
gem "berkshelf"

# TODO remove this when we update Chef to use the new api exposed in 3.5.1
gem "rspec-core", "= 3.4.4"
