source "https://rubygems.org"

gem "chef-acceptance", git: "https://github.com/chef/chef-acceptance"
gem "test-kitchen"
gem "kitchen-ec2"
gem "kitchen-inspec"
gem "kitchen-vagrant"
gem "windows_chef_zero"
gem "winrm-fs"
gem "winrm-elevated"
gem "berkshelf"
gem "inspec", "~> 1.0" # until we pull 2.0 into chefDK

# Workaround to address https://github.com/sickill/rainbow/issues/44
gem "rainbow", ">= 2.1.0", "< 2.2"

# TODO remove this when we update Chef to use the new api exposed in 3.5.1
gem "rspec-core", "= 3.4.4"

# until 2.0.0 is fixed for unstable packages
gem "mixlib-install", "1.2.3"
