driver:
  name: vagrant
  forward_agent: yes
  customize:
    cpus: 2
    memory: 1024

provisioner:
  name: chef_zero
  product_name: <%= ENV["KITCHEN_CHEF_PRODUCT"] %>
  product_version: <%= ENV["KITCHEN_CHEF_VERSION"] %>
  channel: <%= ENV["KITCHEN_CHEF_CHANNEL"] %>
  client_rb:
    audit_mode: :enabled
  attributes:
     chef_acceptance: "true"
     use_system_chef: "true"

# busser installation relies on this
<% if ENV["KITCHEN_CHEF_PRODUCT"] %>
verifier:
  chef_omnibus_root: "/opt/<%= ENV["KITCHEN_CHEF_PRODUCT"] %>"
<% end %>

platforms:
<% %w(
debian-8
debian-7
debian-6
ubuntu-15.10
ubuntu-14.04
el-7
el-6
el-5
freebsd-10
freebsd-9
fedora-21
).each do |platform| %>
  - name: <%= platform %>
    driver:
      box: opscode-<%= platform %>
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_<%= platform %>_chef-provisionerless.box
<% end %>
# freebsd-8
# ubuntu-12.04
# centos-7
  - name: centos-6
    driver:
      box: bento/centos-6.7
<% %w(
2012r2
2012
2008r2
).each do |version| %>
  - name: windows-<%= version %>
    driver:
      box: chef/windows-server-<%= version %>-standard
# URL is atlas
<% end %>
